import type { Metadata } from "next";
import "./globals.css";
import Topbar from "@/components/Topbar";
import Sidebar, { Logout } from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Topbar />
        <Sidebar />
        <Logout />
        {children}
      </body>
    </html>
  );
}
